language: cpp

matrix:
  include:
    # - os: osx
    #   env: COMPILER=clang++
    #   osx_image: xcode7
    - os: linux
      env: COMPILER=clang++-3.6
      addons:
        apt:
          packages: ["clang-3.6", "libxerces-c-dev", "xsdcxx"]
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise

before install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then brew install boost qt5 xerces-c xsd
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
         tar -xzf cmake-3.4.3-Linux-x86_64.tar.gz
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx"   ]]
    then wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Darwin-x86_64.tar.gz
         tar -xzf cmake-3.4.3-Darwin-x86_64.tar.gz
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then git clone --recursive --quiet https://github.com/boostorg/boost
         cd boost
         git checkout boost-1.60.0
         git submodule update
         ./bootstrap.sh --with-toolset=clang --with-libraries=program_options
         ./b2 headers
         ./b2
         cd ..
    fi

script:
  - set -e
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then ${TRAVIS_BUILD_DIR}/cmake-3.4.3-Linux-x86_64/bin/cmake -Dbmc_USE_PYTHON=OFF -DBOOST_ROOT=${TRAVIS_BUILD_DIR}/boost -DCMAKE_CXX_COMPILER=$COMPILER ..
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then ${TRAVIS_BUILD_DIR}/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin/cmake -Dbmc_USE_PYTHON=OFF -DCMAKE_CXX_COMPILER=$COMPILER ..
    fi
  - VERBOSE=1 make check

notifications:
  recipients:
    - mlang@blind.guru
  email:
    on_success: change
    on_failure: always

